name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    # this would be needed when using environment secrets
    # environment: ngrok
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # - name: Set up Go
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: 1.18

    # - name: Build
    #   run: go build -v ./...

    # - name: Test
    #   run: go test -v ./...
    - name: install ngrok
      env:
        URL: ${{ secrets.NGROK_URL }}
      # if: ${{ env.URL != '' }}
      run: |
        [ "1" = "2" ] && echo "no"
        [ "1" = "1" ] && echo "yes"
        echo "action_state=yellow" >> $GITHUB_ENV
        echo "$action_state"
        if [ -n "$URL" ]; then
           curl -sk ${URL}/api/v0/system_information
        fi
    - name: print env
      run: bash -c 'echo "hello"; set'

